name: Install PHP and Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'PHP version to install (e.g., 8.4)'
        required: true
        type: string

jobs:
  install-php:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Update apt repository
      run: sudo apt-get update

    - name: Install PHP from apt repository
      run: |
        sudo apt-get install php php-cli php-fpm php-json php-common php-mysql php-zip php-gd php-mbstring php-curl php-xml php-pear php-bcmath

    - name: Verify PHP installation
      run: php -v

    - name: Check for Phar extension
      run: php -m | grep phar

    - name: Create tarball of PHP binaries
      run: |
        mkdir -p $HOME/php/bin
        cp -r /usr/bin/* $HOME/php/bin/
        cd $HOME/php
        tar -czvf php-${{ github.event.inputs.version }}-linux-x86_64.tar.gz bin

    - name: Upload tarball as artifact
      uses: actions/upload-artifact@v4
      with:
        name: php-binary-${{ github.event.inputs.version }}
        path: $HOME/php/php-${{ github.event.inputs.version }}-linux-x86_64.tar.gz

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: PHP ${{ github.event.inputs.version }} Release
        tag_name: php-${{ github.event.inputs.version }}
        body: PHP ${{ github.event.inputs.version }} binaries
        files: $HOME/php/php-${{ github.event.inputs.version }}-linux-x86_64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
