name: Build & Release PHP

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'PHP version (e.g., 8.2.10)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libxml2-dev libssl-dev libcurl4-openssl-dev pkg-config libonig-dev libsqlite3-dev bison re2c wget

      - name: Download PHP Source
        run: |
          wget https://www.php.net/distributions/php-${{ github.event.inputs.version }}.tar.gz
          tar -xzf php-${{ github.event.inputs.version }}.tar.gz

      - name: Configure & Build PHP CLI
        working-directory: php-${{ github.event.inputs.version }}
        run: |
          ./configure --prefix=$PWD/install --disable-all --enable-cli
          make -j$(nproc)
          make install

      - name: Package Compiled Binary
        run: |
          tar -czvf php-${{ github.event.inputs.version }}-linux-x86_64.tar.gz -C php-${{ github.event.inputs.version }}/install bin

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: "PHP v${{ github.event.inputs.version }} Release"
          body: "PHP CLI binary for version ${{ github.event.inputs.version }} built on Ubuntu x86_64."
          files: |
            php-${{ github.event.inputs.version }}-linux-x86_64.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
